# Generated by Django 5.0.2 on 2025-03-14 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('media_type', models.CharField(choices=[('image', '画像'), ('video', '動画')], max_length=5, verbose_name='メディアタイプ')),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='ファイル')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/', verbose_name='サムネイル')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メディアアイテム',
                'verbose_name_plural': 'メディアアイテム',
                'ordering': ['-created_at'],
            },
        ),
    ]
